from .settings_page import page_default_settings
from .roster_page import page_roster
from .newhire_page import page_new_hire
from .shrink_page import page_shrink_attr
from .budget_page import page_budget
from .dataset_page import page_dataset
from .planning_page import page_planning
from .ops_page import page_ops
from .help_page import page_help
